# Generated by Django 5.1.5 on 2025-04-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_balance',
            field=models.IntegerField(default=0),
        ),
    ]
